/*
 * Copyright (c) Velocity BPA, LLC
 * Licensed under the Business Source License 1.1
 * Commercial use requires a separate commercial license.
 * See LICENSE file for details.
 */

import type {
	IAuthenticateGeneric,
	ICredentialTestRequest,
	ICredentialType,
	INodeProperties,
} from 'n8n-workflow';

/**
 * VeChain Network Credentials
 * Supports multiple networks: Mainnet, Testnet, Thor Solo, and Custom nodes
 * 
 * VeChain uses a dual-token model:
 * - VET: Value token for transactions
 * - VTHO: Energy token (gas) generated by holding VET
 */
export class VechainNetwork implements ICredentialType {
	name = 'vechainNetwork';
	displayName = 'VeChain Network';
	documentationUrl = 'https://docs.vechain.org/';
	properties: INodeProperties[] = [
		{
			displayName: 'Network',
			name: 'network',
			type: 'options',
			options: [
				{
					name: 'Mainnet',
					value: 'mainnet',
					description: 'VeChain Mainnet - Production network',
				},
				{
					name: 'Testnet',
					value: 'testnet',
					description: 'VeChain Testnet - For development and testing',
				},
				{
					name: 'Thor Solo',
					value: 'solo',
					description: 'Local development node',
				},
				{
					name: 'Custom',
					value: 'custom',
					description: 'Custom node URL',
				},
			],
			default: 'mainnet',
			description: 'Select the VeChain network to connect to',
		},
		{
			displayName: 'Node URL',
			name: 'nodeUrl',
			type: 'string',
			default: '',
			placeholder: 'https://mainnet.vechain.org',
			description: 'Custom node URL (leave empty to use default for selected network)',
			displayOptions: {
				show: {
					network: ['custom'],
				},
			},
		},
		{
			displayName: 'Private Key',
			name: 'privateKey',
			type: 'string',
			typeOptions: {
				password: true,
			},
			default: '',
			placeholder: '0x...',
			description: 'Private key in hex format (64 characters, with or without 0x prefix). Required for signing transactions.',
			hint: 'Your private key is never logged or exposed. Keep it secure!',
		},
		{
			displayName: 'Enable Fee Delegation',
			name: 'enableDelegation',
			type: 'boolean',
			default: false,
			description: 'Whether to enable VIP-191 fee delegation (third party pays gas fees)',
		},
		{
			displayName: 'Delegator URL',
			name: 'delegatorUrl',
			type: 'string',
			default: '',
			placeholder: 'https://sponsor.vechain.energy',
			description: 'URL of the fee delegation service',
			displayOptions: {
				show: {
					enableDelegation: [true],
				},
			},
		},
		{
			displayName: 'Delegator Private Key',
			name: 'delegatorPrivateKey',
			type: 'string',
			typeOptions: {
				password: true,
			},
			default: '',
			placeholder: '0x...',
			description: 'Private key of the delegator/sponsor account (optional, for self-sponsoring)',
			displayOptions: {
				show: {
					enableDelegation: [true],
				},
			},
		},
	];

	authenticate: IAuthenticateGeneric = {
		type: 'generic',
		properties: {},
	};

	test: ICredentialTestRequest = {
		request: {
			baseURL: '={{$credentials.network === "custom" ? $credentials.nodeUrl : ($credentials.network === "mainnet" ? "https://mainnet.veblocks.net" : ($credentials.network === "testnet" ? "https://testnet.veblocks.net" : "http://localhost:8669"))}}',
			url: '/blocks/best',
			method: 'GET',
		},
	};
}
